name: C/C++ CI

on:
  push:
    branches: [ "main" ,"static_lib"]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env

    - name: configure
      run: cp -r ../* /opt/
    - run: ls
      working-directory: /opt/State-Machine

    - run: mkdir ./build 
    - name: cmake
      run: cmake -B ./build
    - run: make -C ./build -j 12
