name: C/C++ CI

on:
  push:
    branches: [ "main" ,"static_lib"]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run:  mkdir /opt/lib
    - name: configure
      run: mv . /opt/lib
    - run: |
        ls /opt/lib
